default:
  broker:
{{#each asyncapi.__schemes as |scheme|}}
  {{#compare scheme '===' 'amqp'}}
    amqp:
      exchange:
      username:
      password:
      host: localhost
      port:
      topic: {{../../asyncapi.__commonTopic}}
      queue: {{queueName ../../asyncapi.info.title ../../asyncapi.info.version}}
      queue_options:
        exclusive: false
        durable: true
        autoDelete: true
  {{/compare}}
  {{#compare scheme '===' 'mqtt'}}
    mqtt:
      host_url: mqtt://localhost
      topics: {{toMQTT ../../asyncapi.__commonTopic}}
      qos:
      protocol: mqtt
      retain:
  {{/compare}}
{{/each}}


development:

test:

staging:

production:
  broker:
{{#each asyncapi.__schemes as |scheme|}}
  {{#compare scheme '===' 'amqp'}}
    amqp:
      host: {{../../asyncapi.host}}
  {{/compare}}
  {{#compare scheme '===' 'mqtt'}}
    mqtt:
      host_url: mqtt://{{../../asyncapi.host}}
  {{/compare}}
{{/each}}
